#!/bin/sh
# ~/.config/aliasrc

# to make aliases work with sudo (note the trailing space)
alias sudo='sudo '

alias ls='ls --color'
alias ll='ls -alhF'
alias la='ls -A'
alias l='ls -1'
#alias ld='ls -d */'

alias grep='grep --color'
alias less='less -R'
alias ..='cd ..'
alias odilia='feh -ZsdSname --hide-pointer -B black'
alias dh='df -hx tmpfs -x devtmpfs'

alias ffmpeg='ffmpeg -hide_banner'
alias ffprobe='ffprobe -hide_banner'

